version: '3.3'

services:
  postgres_DB:
    restart: always
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=atomDB
      - POSTGRES_USER=dimitris
      - POSTGRES_PASSWORD=secret
  redis_DB:
    restart: always
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
